Repository Premkolte/AnimateHub, pull requests merged in 2024-06, with the labels that each got.

#22 Added Radio Snippets
  src/components/RadioSnippets.jsx
  src/components/Window.jsx
Labels: VSoC’24, Medium

#23 Improved folder structure
  src/components/CheckboxSnippets.jsx
  src/components/Inputfield.jsx
  src/components/SnippetComponents/ButtonSnippets.jsx
  src/components/SnippetComponents/CardSnippets.jsx
  src/components/SnippetComponents/CheckboxSnippets.jsx
  src/components/SnippetComponents/DropdownSnippets.jsx
  src/components/SnippetComponents/InputfieldSnippets.jsx
  src/components/SnippetComponents/RadioSnippets.jsx
  src/components/SnippetComponents/Snippets/Buttons.js
  src/components/SnippetComponents/Snippets/Cards.js
  src/components/SnippetComponents/Snippets/CheckBoxes.js
  src/components/SnippetComponents/Snippets/DropDowns.js
  src/components/SnippetComponents/Snippets/InputFields.js
  src/components/SnippetComponents/Snippets/Radios.js
  src/components/Window.jsx
Labels: VSoC’24, Medium

#28 added sign up snippet
  src/components/SideBar.jsx
  src/components/SnippetComponents/SignupSnippets.jsx
  src/components/SnippetComponents/Snippets/SignUp.js
  src/components/Window.jsx
Labels: VSoC’24, Medium

#31 added toggle switch snippets
  src/components/Modal.jsx
  src/components/SideBar.jsx
  src/components/SnippetComponents/Snippets/ToggleSwitch.js
  src/components/SnippetComponents/ToggleSwitchSnippets.jsx
  src/components/Window.jsx
Labels: VSoC’24, Medium

#34 Added Toggle switch components
  src/components/SnippetComponents/Snippets/ToggleSwitch.js
  src/components/SnippetComponents/ToggleSwitchSnippets.jsx
  src/components/Window.jsx
Labels: VSoC’24, Medium

#39 Updated folder structure
  README.md
Labels: VSoC’24, Easy

#38 Added animated cursor
  package-lock.json
  package.json
  src/App.jsx
Labels: VSoC’24, Medium

#46 added slideshow and scroll bar to side bar
  src/components/SideBar.jsx
  src/components/SnippetComponents/SlideShowSnippets.jsx
  src/components/SnippetComponents/Snippets/Slideshows.js
  src/components/Window.jsx
  src/constants/Buttons.js
Labels: VSoC’24, Medium

#51 added text snippets and box shdow snippets
  src/components/SnippetComponents/BoxShadowSnippets.jsx
  src/components/SnippetComponents/Snippets/BoxShadow.js
  src/components/SnippetComponents/Snippets/Text.js
  src/components/SnippetComponents/TextSnippets.jsx
  src/components/Window.jsx
Labels: VSoC’24, Medium

#55 updated form snippets (added contact and proceed to checkout form)
  src/components/Modal.jsx
  src/components/SnippetComponents/FormSnippets.jsx
  src/components/SnippetComponents/Snippets/Buttons.js
  src/components/SnippetComponents/Snippets/Form.js
  src/components/Window.jsx
Labels: VSoC’24, Hard

#61 added homepage
  package-lock.json
  package.json
  src/App.jsx
  src/components/Home/HomePage.jsx
  src/components/Home/Navbar.jsx
Labels: VSoC’24, Hard

#62 Add Greetings
  .github/workflows/greetings.yml
  README.md
Labels: VSoC’24, Medium

#64 added dark mode and contact and about page
  src/App.jsx
  src/components/About/AboutUs.jsx
  src/components/Contact/ContactUs.jsx
  src/components/Home/DarkModeToggle.jsx
  src/components/Home/HomePage.jsx
  src/components/Home/Navbar.jsx
  src/components/SideBar.jsx
Labels: VSoC’24, Medium

#71 Add Contributors
  .all-contributorsrc
  .github/workflows/add-contributors.yml
  README.md
  package-lock.json
  package.json
Labels: VSoC’24, Medium

#74 Landing Page
  src/App.jsx
  src/components/About/AboutUs.jsx
  src/components/Contact/ContactUs.jsx
  src/components/DarkModeToggle.jsx
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/components/Home/HomePage.jsx
  src/components/Home/Navbar.jsx
  src/components/Navbar.jsx
  src/components/Window.jsx
Labels: VSoC’24, Hard

#76 Contributors page
  src/App.jsx
  src/components/Contributors/Contributors.jsx
  src/components/Home/HomePage.jsx
Labels: VSoC’24, Medium

#80 updated contact page
  src/App.jsx
  src/components/About/AboutUs.jsx
  src/components/Contact/ContactUs.jsx
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/Home/HomePage.jsx
  src/components/Navbar.jsx
  src/components/SnippetComponents/NavbarIconSnippets.jsx
  src/components/SnippetComponents/Snippets/NavbarIcon.js
Labels: VSoC’24, Easy

#94 added templates
  src/App.jsx
  src/components/Home/HomePage.jsx
  src/components/TemplatesFiles/Blog.jsx
  src/components/TemplatesFiles/Portfoilo.jsx
  src/components/TemplatesFiles/Product.jsx
Labels: VSoC’24, Medium

#95 about and contact pages
  src/components/About/AboutUs.jsx
  src/components/Contact/ContactUs.jsx
Labels: VSoC’24, Medium

#101 updated blog and product page
  src/components/TemplatesFiles/Blog.jsx
  src/components/TemplatesFiles/Product.jsx
Labels: VSoC’24, Medium

#102 Responsive Navbar
  src/components/Navbar.jsx
Labels: VSoC’24, Medium

#105 chore: Removed navbar from pages except Home
  src/App.jsx
  src/components/About/AboutUs.jsx
  src/components/Contact/ContactUs.jsx
  src/components/Contributors/Contributors.jsx
  src/components/Home/HomePage.jsx
  src/components/Home/Navbar.jsx
Labels: VSoC’24, Medium

#108 templates page
  src/App.jsx
  src/components/About/AboutUs.jsx
  src/components/BackButton.jsx
  src/components/Contact/ContactUs.jsx
  src/components/Footer.jsx
  src/components/Home/HomePage.jsx
  src/components/Templates/AvailableTemplates.js
  src/components/Templates/Blog.jsx
  src/components/Templates/Portfolio.jsx
  src/components/Templates/Product.jsx
  src/components/Templates/TemplateCard.jsx
  src/components/Templates/TemplatesPage.jsx
  src/components/Templates/TemplatesRoutes.jsx
Labels: VSoC’24, Medium
