Repository Premkolte/AnimateHub, pull requests merged in 2024-07, with the labels that each got.

#115 Navbar for templates
  src/components/Templates/Blog.jsx
  src/components/Templates/Portfolio.jsx
  src/components/Templates/Product.jsx
  src/components/Templates/TemplateNavBar.jsx
Labels: VSoC’24, Medium

#116 code: star github button
  src/components/Home/HomePage.jsx
Labels: VSoC’24, Easy

#117 Update AvailableTemplates.js
  src/components/Templates/AvailableTemplates.js
Labels: VSoC’24, Medium

#119 added more snippets and google button
  src/components/Auth/SignUp.jsx
  src/components/Auth/login.jsx
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/AvatarImageSnippets.jsx
  src/components/SnippetComponents/BadgeSnippets.jsx
  src/components/SnippetComponents/ColorPickerSnippets.jsx
  src/components/SnippetComponents/FooterSnippets.jsx
  src/components/SnippetComponents/Snippets/AvatarImage.js
  src/components/SnippetComponents/Snippets/Badge.js
  src/components/SnippetComponents/Snippets/ColorPicker.js
  src/components/SnippetComponents/Snippets/Footer.js
Labels: VSoC’24, Medium

#121 added tour
  package-lock.json
  package.json
  src/components/Home/HomePage.jsx
Labels: VSoC’24, Hard

#125 Fix : Copyright year bug
  src/components/Footer.jsx
Labels: VSoC’24, Easy

#130 Updating workflow
  .all-contributorsrc
  .github/workflows/add-contributors.yml
  README.md
Labels: VSoC’24, Hard, bonus-points

#137 added pegination and pill navigation
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/PaginationSnippets.jsx
  src/components/SnippetComponents/PillNavigationSnippets.jsx
  src/components/SnippetComponents/Snippets/Pagination.js
  src/components/SnippetComponents/Snippets/PillNavigation.js
Labels: VSoC’24, Medium

#142 added news letter
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/NewsLetterSnippets.jsx
  src/components/SnippetComponents/Snippets/NewsLetter.js
  src/components/SnippetComponents/Snippets/Sort.js
  src/components/SnippetComponents/SortSnippets.jsx
Labels: VSoC’24, Medium

#143 added sort snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/Snippets/Sort.js
  src/components/SnippetComponents/SortSnippets.jsx
Labels: VSoC’24, Medium

#145 added coupon
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/CouponSnippets.jsx
  src/components/SnippetComponents/Snippets/Coupon.js
Labels: VSoC’24, Medium

#148 Feat : Added Hide/Unhide functionality
  src/components/Auth/SignUp.jsx
Labels: VSoC’24, Medium

#151 Feat : Fully new version of readme.md file
  README.md
Labels: VSoC’24, Hard

#162 Fix Button Redirection for "Become a Contributor" and "Submit a Template"
  src/components/Home/HomePage.jsx
Labels: VSoC’24, Easy

#163 Added : CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: VSoC’24, Medium

#167 Added CONTRIBUITING.md file in repo
  CONTRIBUITING.md
Labels: VSoC’24, Medium

#170 Updated Favicon
  Logo.png
  favicon.ico
Labels: VSoC’24, Easy

#171 Fix Dashboard Height and Make Content Scrollable
  package-lock.json
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/index.css
Labels: VSoC’24, Medium

#174 Features
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/Snippets/Social.js
  src/components/SnippetComponents/Snippets/Tab.js
  src/components/SnippetComponents/TabGroup.jsx
  src/index.css
Labels: VSoC’24, bonus-points

#175 added shades
  package-lock.json
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/AnimationIcon.jsx
  src/components/SnippetComponents/QuoteSlideSnippets.jsx
  src/components/SnippetComponents/ShadeSnippets.jsx
  src/components/SnippetComponents/Snippets/Shade.js
Labels: VSoC’24, Medium

#178 added animation icon snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/AnimationIcon.jsx
  src/components/SnippetComponents/Snippets/AnimationIcon.js
Labels: VSoC’24, Medium

#180 countDown Snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/CountDownSnippets.jsx
  src/components/SnippetComponents/Snippets/CountDown.js
Labels: VSoC’24, Medium

#181 Updated Readme.md
  README.md
Labels: VSoC’24, Easy

#184 added textArea snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/PricingSnippets.jsx
  src/components/SnippetComponents/Snippets/Pricing.js
  src/components/SnippetComponents/Snippets/TextArea.js
  src/components/SnippetComponents/TextAreaSnippets.jsx
Labels: VSoC’24, Medium

#185 added pricing snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
Labels: VSoC’24, Medium

#187 solved snippets bug
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/ProfileCardSnippets.jsx
  src/components/SnippetComponents/Snippets/ProfileCard.js
Labels: VSoC’24, Medium

#188 added profile snippets
  src/components/Dashboard/Buttons.js
  src/components/SnippetComponents/Snippets/ProfileCard.js
Labels: VSoC’24, Medium

#190 added tab group component
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/Snippets/Tab.js
  src/components/SnippetComponents/TabGroup.jsx
Labels: VSoC’24, Medium

#191 added favicon
  favicon.ico
  index.html
  public/Favicon.png
Labels: VSoC’24, Medium

#195 Update add-contributors.yml
  .github/workflows/add-contributors.yml
Labels: VSoC’24, Medium

#196 Adding `FAQ` to the `Contact Us` page
  src/assets/FAQ.jsx
  src/components/Contact/ContactUs.jsx
Labels: VSoC’24, Medium

#197 Add snippets
  src/components/SnippetComponents/Snippets/AnimationIcon.js
  src/components/SnippetComponents/Snippets/Buttons.js
  src/components/SnippetComponents/Snippets/DropDowns.js
  src/components/SnippetComponents/Snippets/Page-load.js
Labels: VSoC’24, Hard, bonus-points

#198 added logo in homepage
  Favicon.png
  index.html
  package-lock.json
  public/Favicon.png
  src/components/Home/Navbar.jsx
  src/components/Home/images/Animate_logo.png
  src/index.css
  tailwind.config.js
Labels: VSoC’24, Medium
