Repository Premkolte/AnimateHub, pull requests merged in 2025-09, with the labels that each got.

#637 Added Comment Schema and setup Router for it
  backend/src/app.js
  backend/src/controllers/comment.controller.js
  backend/src/models/comment.model.js
  backend/src/routes/comment.route.js
Labels: GSSoC'25, Level2

#639 Google Sign in Added
  backend/.env.example
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/auth.controller.js
  backend/src/controllers/googleAuth.controller.js
  backend/src/routes/auth.route.js
  backend/src/services/emailService.js
  package-lock.json
  package.json
  src/Pages/Auth/LoginPage.jsx
  src/Pages/Auth/SignUpPage.jsx
  src/main.jsx
  src/store/authStore.js
Labels: GSSoC'25, Level3

#640 fixed port
  backend/index.js
Labels: GSSoC'25, Level1

#641 Added Controllers
  backend/src/controllers/comment.controller.js
  backend/src/routes/comment.route.js
Labels: GSSoC'25, Level3

#642 Added font playground
  src/App.jsx
  src/Pages/Playground/FontPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#631 Enhance Homepage UI & Experience
  package-lock.json
  package.json
  src/Pages/Home/HeroSection.jsx
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/Testimonial.jsx
Labels: GSSoC'25, Level3

#645 Improve ui of the Font playground
  src/Pages/Playground/FontPlayground.jsx
  src/Pages/Playground/FramerPlayground.jsx
Labels: GSSoC'25, Level3

#646 Feature: Add GSAP ScrollTrigger animations to Pricing section
  src/Pages/Home/Pricing.jsx
Labels: GSSoC'25, Level2

#643 Feature: Add GSAP ScrollTrigger animations to Feature cards
  package-lock.json
  src/Pages/Home/HomePage.jsx
Labels: GSSoC'25, Level3

#651 Done major changes on homepage
  src/Pages/Home/HeroSection.jsx
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/LandPage.jsx
  src/Pages/Home/Pricing.jsx
Labels: GSSoC'25, Level3

#654 Fix: Chatbot & Scroll-to-Top Icons Overflow on About Page
  src/Pages/About/AboutUs.jsx
Labels: GSSoC'25, Level1

#657 Enhance newsletter subscription validation with error notifications
  src/Pages/Home/Subscribe.jsx
Labels: GSSoC'25, Level2

#660 Remove twitter logo with x logo
  src/components/layout/Footer.jsx
Labels: GSSoC'25, Level1

#661 Added update and getcomments controller
  backend/src/controllers/comment.controller.js
  backend/src/routes/comment.route.js
Labels: GSSoC'25, Level2

#666 Remade Homepage UI, Removed Unprofessional Decorative Elements & Refactored Component Structure #663
  src/Pages/Home/Contributors.jsx
  src/Pages/Home/FeaturesSection.jsx
  src/Pages/Home/HeroSection.jsx
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/LandPage.jsx
  src/Pages/Home/Pricing.jsx
  src/Pages/Home/TemplatesSection.jsx
  src/Pages/Home/Testimonial.jsx
  src/components/UI/DarkModeToggle.jsx
Labels: GSSoC'25, Level3

#667 Made the buttons redirecting to their proper endpoints
  src/Pages/Home/HeroSection.jsx
Labels: GSSoC'25, Level2

#673 Add search functionality to leaderboard for easier user lookup
  src/Pages/Home/HeroSection.jsx
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level2

#675 feat: add centralized error handling middleware
  backend/src/app.js
Labels: GSSoC'25, Level2

#686 Added Introduction Page to Components Route & Fixed Link Redirections
  src/App.jsx
  src/Pages/Components/ComponentsPage.jsx
  src/Pages/Components/components/ComponentsBase.jsx
  src/Pages/Components/staticPages/InstallationPage.jsx
  src/Pages/Components/staticPages/IntroductionPage.jsx
  src/Pages/Components/staticPages/ThemingPage.jsx
Labels: GSSoC'25, Level3

#689 Added a FlexBox playGround
  src/App.jsx
  src/Pages/Playground/FlexboxPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#690 Added functionality to Show CSS Button and React Snippet
  index.css
  src/Pages/Home/HeroSection.jsx
  src/components/SnippetComponents/AccordianSnippets.jsx
  src/components/UI/Modal.jsx
  src/index.css
  src/utils/snippets.js
Labels: GSSoC'25, Level3

#691 improved FlexBox Playground Using Modern effects
  src/Pages/Playground/FlexboxPlayground.jsx
Labels: GSSoC'25, Level3

#692 [FIX]: #688 Inconsistent Icon Behavior and Text Flickering on Contact Page
  src/Pages/Contact/ContactUs.jsx
Labels: GSSoC'25, Level2

#693 Fix: active state & UI for Playgrounds
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#694 Remade Navbar with Clean, Organized & Readable Code #384
  src/App.jsx
  src/components/Home/HomePage.jsx
  src/components/layout/Navbar.css
  src/components/layout/Navbar.jsx
  src/components/layout/NavbarComponents/MobileNav.jsx
  src/components/layout/NavbarComponents/NavbarProfile.jsx
Labels: GSSoC'25, Level3

#698 Added a GridPlayGround
  src/App.jsx
  src/Pages/Playground/GridPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#722 Enhanced sitemap.xml with SEO-friendly updates (Level 3 Contribution)
  public/sitemap.xml
Labels: GSSoC'25, Level3

#741 feat: changed favicon to transparent
  Favicon.png
  Favicon1.png
Labels: GSSoC'25, Level2

#742 Footer dark/light mode correction
  package-lock.json
  package.json
  src/components/layout/Footer.jsx
Labels: GSSoC'25, Level3

#743 Refactor LeaderBoard component for improved readability and maintainability
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level2

#745 Separate form for Blog Posting
  src/App.jsx
  src/Pages/AddBlogPage.jsx
  src/Pages/BlogPage.jsx
Labels: GSSoC'25, Level3

#750 textVisibility_in_mobileNavabr
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level2

#752 Refactor auth.controller.js for cleaner structure and consistency
  backend/src/controllers/auth.controller.js
Labels: GSSoC'25, Level3

#755 Added a Resuable BlogModal Component
  src/Pages/BlogPage.jsx
  src/components/BlogReadModal.jsx
Labels: GSSoC'25, Level3

#756 fix: enhance hover effects for tech icons and buttons in HeroSection
  src/Pages/Home/HeroSection.jsx
Labels: GSSoC'25, Level2

#757 Improved the BlogReadModal
  src/components/BlogReadModal.jsx
Labels: GSSoC'25, Level3

#769 Level 3 Update: Routing, UX, and Deploy-ready Improvements
  src/App.jsx
Labels: GSSoC'25, Level3

#771 Issue no. 760
  src/Pages/About/GitHubStats.jsx
Labels: GSSoC'25, Level2

#774 Added the contributing guidelines fix
  CONTRIBUTING.md
Labels: GSSoC'25, Level1

#777 Added a reusbale BlogCard component
  src/Pages/BlogPage.jsx
  src/components/BlogCard.jsx
Labels: GSSoC'25, Level3

#783 Redesign the complete about us page
  src/Pages/About/AboutUs.jsx
Labels: GSSoC'25, Level3

#786 Bug/fixe close btn mobile navbar
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level2

#787 Added a Transform Playground
  src/App.jsx
  src/Pages/Playground/TransformPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#789 chore: apply level 3 changes to vite.config.js
  vite.config.js
Labels: GSSoC'25, Level2

#799 fixes text visibility in playground section
  src/Pages/Playground/FramerPlayground.jsx
Labels: GSSoC'25, Level1

#800 fixes text visibility in template section
  src/components/Templates/TemplatesPage.jsx
Labels: GSSoC'25, Level2

#801 Form validation on contact page
  src/Pages/Contact/ContactUs.jsx
Labels: GSSoC'25, Level3

#835 Complete SVG Playground Overhaul: Real-time Animation Studio
  src/Pages/Playground/SVGPlayground.jsx
Labels: GSSoC'25, Level3
