Repository Premkolte/AnimateHub, pull requests merged in 2025-08, with the labels that each got.

#251 resolved issue #250
  src/App.jsx
  src/components/Contributors/Contributors.jsx
Labels: GSSoC'25, Level2

#252 Fixed Dark/Light Theme Toggle + Improved Text Contrast Across UI – Closes #242
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/components/Home/Navbar.jsx
  src/components/Modal.jsx
  src/components/SnippetComponents/AnimationIcon.jsx
  src/components/SnippetComponents/AnimationSnippets.jsx
  src/components/SnippetComponents/AvatarImageSnippets.jsx
  src/components/SnippetComponents/BadgeSnippets.jsx
  src/components/SnippetComponents/BoxShadowSnippets.jsx
  src/components/SnippetComponents/ButtonSnippets.jsx
  src/components/SnippetComponents/CardSnippets.jsx
  src/components/SnippetComponents/CheckboxSnippets.jsx
  src/components/SnippetComponents/ColorPickerSnippets.jsx
  src/components/SnippetComponents/CountDownSnippets.jsx
  src/components/SnippetComponents/CouponSnippets.jsx
  src/components/SnippetComponents/DarkModeSnippets.jsx
  src/components/SnippetComponents/DropdownSnippets.jsx
  src/components/SnippetComponents/ExpandingSearchBar.jsx
  src/components/SnippetComponents/FooterSnippets.jsx
  src/components/SnippetComponents/FormSnippets.jsx
  src/components/SnippetComponents/InputfieldSnippets.jsx
  src/components/SnippetComponents/LoginSnippets.jsx
  src/components/SnippetComponents/NavbarIconSnippets.jsx
  src/components/SnippetComponents/NeonButton.jsx
  src/components/SnippetComponents/NewsLetterSnippets.jsx
  src/components/SnippetComponents/PageLoaderSnippets.jsx
  src/components/SnippetComponents/PaginationSnippets.jsx
  src/components/SnippetComponents/PaymentFormSnippets.jsx
  src/components/SnippetComponents/PillNavigationSnippets.jsx
  src/components/SnippetComponents/PricingSnippets.jsx
  src/components/SnippetComponents/ProfileCardSnippets.jsx
  src/components/SnippetComponents/ProgressBarSnippets.jsx
  src/components/SnippetComponents/QuoteSlideSnippets.jsx
  src/components/SnippetComponents/RadioSnippets.jsx
  src/components/SnippetComponents/ResponsivenessSnippets.jsx
  src/components/SnippetComponents/ShadeSnippets.jsx
  src/components/SnippetComponents/SignupSnippets.jsx
  src/components/SnippetComponents/SlideShowSnippets.jsx
  src/components/SnippetComponents/SocialSnippets.jsx
  src/components/SnippetComponents/SortSnippets.jsx
  src/components/SnippetComponents/TabGroup.jsx
  src/components/SnippetComponents/TableSnippets.jsx
  src/components/SnippetComponents/TextAreaSnippets.jsx
  src/components/SnippetComponents/TextSnippets.jsx
  src/components/SnippetComponents/ToggleSwitchSnippets.jsx
Labels: GSSoC'25, Level3

#255 feat: add back-to-top button and scroll-based chatbot animation
  src/App.jsx
  src/components/BackToTop.jsx
  src/components/Home/Chatbot.jsx
  src/index.css
Labels: GSSoC'25, Level2

#260 Added light mode theme support for Contact Us and About Us
  src/assets/FAQ.jsx
  src/components/About/AboutUs.jsx
  src/components/BackButton.jsx
  src/components/Contact/ContactUs.jsx
Labels: GSSoC'25, Level2

#263 [Feat]:Setup Auth Successfully
  .env.example
  package-lock.json
  package.json
  src/App.jsx
  src/components/Auth/ProtectedRoute.jsx
  src/components/Auth/SignUp.jsx
  src/components/Auth/login.jsx
  src/components/Home/Navbar.jsx
  src/main.jsx
Labels: GSSoC'25, Level3

#277 enhanced the about page and now it looks better
  DEVELOPMENT_SETUP.md
  src/components/About/AboutUs.jsx
Labels: GSSoC'25, Level2

#282 feat: Add Forgot Password feature
  src/App.jsx
  src/components/Auth/ForgotPasswordPage.jsx
  src/components/Auth/login.jsx
Labels: GSSoC'25, Level2

#285 Added Hover Animation for Testimonials, Features, Pricing components
  src/components/Home/HomePage.jsx
  src/components/Home/Testimonial.jsx
Labels: GSSoC'25, Level2

#289 updated testimonial section
  src/components/Home/Testimonial.jsx
Labels: GSSoC'25

#297 [FEAT] :- Modern Chatbot UI Enhancement
  src/components/Home/Chatbot.jsx
Labels: GSSoC'25, Level3

#299 Feature : Multilingual feature
  index.css
  index.html
  package-lock.json
  package.json
  src/components/Home/Navbar.jsx
Labels: GSSoC'25, Level3

#300 Refactor Contributors Page for UI Consistency & Theming Support (#290)
  src/components/Contributors/Contributors.jsx
Labels: GSSoC'25, Level3

#302 Fix bug 298
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/SideBar.jsx
  src/components/Home/Navbar.jsx
  src/components/SnippetComponents/Snippets/ProfileCard.js
Labels: GSSoC'25, Level2

#305 Fix Homepage Layout Shift & Browse Animation Overlap (#292)
  src/components/Home/HomePage.jsx
Labels: GSSoC'25, Level3

#309 Backend Authentication System – Signup, Login, Logout & Email Transporter Setup #308
  backend/.env.example
  backend/Readme.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/.gitkeep
  backend/src/controllers/auth.controller.js
  backend/src/models/.gitkeep
  backend/src/models/user.model.js
  backend/src/routes/.gitkeep
  backend/src/routes/auth.route.js
  backend/src/services/EmailTemplates/AccountDelete.email.js
  backend/src/services/EmailTemplates/ForgotPassword.email.js
  backend/src/services/EmailTemplates/PasswordChanged.email.js
  backend/src/services/EmailTemplates/VerifyAccount.email.js
  backend/src/services/EmailTransporter.js
  backend/src/utils/asyncHandler.js
Labels: GSSoC'25, Level3

#313 Add Accordion, Modal, and Tooltip Components + Fix Box Shadow Snippets
  src/components/Dashboard/Buttons.js
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/AccordianSnippets.jsx
  src/components/SnippetComponents/ModalSnippets.jsx
  src/components/SnippetComponents/Snippets/Accordion.js
  src/components/SnippetComponents/Snippets/BoxShadow.js
  src/components/SnippetComponents/Snippets/Modal.js
  src/components/SnippetComponents/Snippets/Tooltip.js
  src/components/SnippetComponents/TooltipSnippets.jsx
Labels: GSSoC'25, Level3

#320 Changed the Cursor
  package-lock.json
  package.json
  src/App.jsx
  src/components/SplashCursor.jsx
Labels: GSSoC'25, Level2

#323 signIn signUP UI enhanced
  src/components/Auth/SignUp.jsx
  src/components/Auth/login.jsx
Labels: GSSoC'25, Level2

#331 feat(typography): use Poppins for body text and Sora for headings; improved overall UI consistency
  index.css
  index.html
  src/components/Home/Navbar.jsx
  tailwind.config.js
Labels: GSSoC'25, Level2

#335 enhanced the explore page completely in dark mode
  package-lock.json
  src/components/Dashboard/SideBar.jsx
  src/components/Dashboard/Window.jsx
  src/components/SnippetComponents/AccordianSnippets.jsx
  src/components/SnippetComponents/AnimationIcon.jsx
  src/components/SnippetComponents/AnimationSnippets.jsx
  src/components/SnippetComponents/AvatarImageSnippets.jsx
  src/components/SnippetComponents/BadgeSnippets.jsx
  src/components/SnippetComponents/BoxShadowSnippets.jsx
  src/components/SnippetComponents/ButtonSnippets.jsx
  src/components/SnippetComponents/CardSnippets.jsx
  src/components/SnippetComponents/CheckboxSnippets.jsx
  src/components/SnippetComponents/ColorPickerSnippets.jsx
  src/components/SnippetComponents/CountDownSnippets.jsx
  src/components/SnippetComponents/CouponSnippets.jsx
  src/components/SnippetComponents/DarkModeSnippets.jsx
  src/components/SnippetComponents/DropdownSnippets.jsx
  src/components/SnippetComponents/ExpandingSearchBar.jsx
  src/components/SnippetComponents/FooterSnippets.jsx
  src/components/SnippetComponents/FormSnippets.jsx
  src/components/SnippetComponents/InputfieldSnippets.jsx
  src/components/SnippetComponents/LoginSnippets.jsx
  src/components/SnippetComponents/ModalSnippets.jsx
  src/components/SnippetComponents/NavbarIconSnippets.jsx
  src/components/SnippetComponents/NeonButton.jsx
  src/components/SnippetComponents/NewsLetterSnippets.jsx
  src/components/SnippetComponents/PageLoaderSnippets.jsx
  src/components/SnippetComponents/PaginationSnippets.jsx
  src/components/SnippetComponents/PaymentFormSnippets.jsx
  src/components/SnippetComponents/PillNavigationSnippets.jsx
  src/components/SnippetComponents/PricingSnippets.jsx
  src/components/SnippetComponents/ProfileCardSnippets.jsx
  src/components/SnippetComponents/ProgressBarSnippets.jsx
  src/components/SnippetComponents/QuoteSlideSnippets.jsx
  src/components/SnippetComponents/RadioSnippets.jsx
  src/components/SnippetComponents/ResponsivenessSnippets.jsx
  src/components/SnippetComponents/ShadeSnippets.jsx
  src/components/SnippetComponents/SignupSnippets.jsx
  src/components/SnippetComponents/SlideShowSnippets.jsx
  src/components/SnippetComponents/SocialSnippets.jsx
  src/components/SnippetComponents/SortSnippets.jsx
  src/components/SnippetComponents/TabGroup.jsx
  src/components/SnippetComponents/TableSnippets.jsx
  src/components/SnippetComponents/TextAreaSnippets.jsx
  src/components/SnippetComponents/TextSnippets.jsx
  src/components/SnippetComponents/ToggleSwitchSnippets.jsx
  src/components/SnippetComponents/TooltipSnippets.jsx
  src/main.jsx
  tailwind.config.js
Labels: GSSoC'25, Level3

#337 Complete Backend Authentication System — Email Verification, Password Management & More (#311)
  backend/.env.example
  backend/src/controllers/auth.controller.js
  backend/src/controllers/user.controller.js
  backend/src/middlewares/.gitkeep
  backend/src/middlewares/auth.middleware.js
  backend/src/models/user.model.js
  backend/src/routes/auth.route.js
  backend/src/services/EmailTemplates/ForgotPassword.email.js
  backend/src/services/EmailTemplates/VerifyAccount.email.js
  backend/src/services/emailService.js
Labels: GSSoC'25, Level3

#344 dd GitHub Link with Icon to Footer for Easy Navigation
  src/components/Footer.jsx
Labels: GSSoC'25, Level1

#355 fix: Homepage UI improvement (navbar and overscroll)
  src/components/Home/Navbar.jsx
  src/index.css
Labels: GSSoC'25, Level2

#358 Add React Hot Toast for User Notifications Across the App (#353) + Fix Router Implementation
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/Auth/LoginPage.jsx
  src/Pages/Auth/SignUpPage.jsx
  src/Pages/Payment/Payment.jsx
  src/store/authStore.js
Labels: GSSoC'25, Level2

#359 enhanced overall homepage spacing, sections, effects, animations and background in light mode
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/Testimonial.jsx
  src/components/layout/Footer.jsx
Labels: GSSoC'25, Level3

#363 Fixed Navbar Title and Description Colors for Light and Dark Themes
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level1

#364 Enhancing mobile nav
  src/components/layout/Navbar.css
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level2

#367 Add Dynamic GitHub Stats Section to Aboutpage
  package-lock.json
  package.json
  src/Pages/About/AboutUs.jsx
  src/Pages/About/GitHubStats.jsx
  src/Pages/Home/Testimonial.jsx
Labels: GSSoC'25, Level2

#371 add dynamic greeting with gradient, input, and change button
  package-lock.json
  package.json
  src/Pages/Home/DynamicGreeting.jsx
  src/Pages/Home/HomePage.jsx
Labels: GSSoC'25, Level3

#372 add custom code snippet
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/Dashboard/MySnippet.jsx
  src/Pages/Dashboard/SideBar.jsx
  src/Pages/Dashboard/mysnippet.css
Labels: GSSoC'25, Level3

#374 Fully Integrated Remaining Auth Routes with Frontend (#352)
  backend/src/controllers/auth.controller.js
  backend/src/controllers/user.controller.js
  package-lock.json
  src/App.jsx
  src/Pages/Auth/LoginPage.jsx
  src/Pages/Auth/ProtectedRoute.jsx
  src/Pages/Auth/ResetPasswordPage.jsx
  src/Pages/Auth/VerifyEmail.jsx
  src/Pages/Auth/components/ResendEmailVerificationButton.jsx
  src/Pages/Home/HomePage.jsx
  src/store/authStore.js
Labels: GSSoC'25, Level3

#381 [FIX] Adjust navbar alignment #380
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level1

#391 refactor: optimize user controllers by using .select() to exclude sen…
  backend/src/controllers/user.controller.js
Labels: GSSoC'25, Level2

#393 added playground with live preview
  src/App.jsx
  src/Pages/AnimationPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#398 remove warnings and errors for process is undefined
  eslint.config.js
Labels: GSSoC'25, Level2

#399 Updated the loader for its proper working
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level1

#407 enhanced the whole sidebar
  src/Pages/Dashboard/SideBar.jsx
Labels: GSSoC'25, Level2

#410 Feat: add prefers-reduced-motion support for accessibility
  src/Pages/About/AboutUs.jsx
  src/Pages/Contact/FAQ.jsx
  src/components/SnippetComponents/Snippets/Buttons.js
  src/components/SnippetComponents/Snippets/Modal.js
  src/components/SnippetComponents/Snippets/NavbarIcon.js
  src/components/SnippetComponents/Snippets/ToggleSwitch.js
  src/components/SnippetComponents/Snippets/Tooltip.js
Labels: GSSoC'25, Level2

#416 navbar fixed
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level2

#417 Refactored Leaderboard UI & Fixed Footer Positioning (#383)
  src/App.jsx
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level3

#418 Standardized UI Across Pages to Match App’s Overall Design (#387)
  src/components/Templates/Blog.jsx
  src/components/Templates/Portfolio.jsx
  src/components/Templates/Product.jsx
  src/components/Templates/TemplatesPage.jsx
Labels: GSSoC'25, Level3

#421 Add Sidebar for Small Screens
  src/Pages/Dashboard/SideBar.jsx
Labels: GSSoC'25, Level2

#420 added search option and sort dropdown
  src/Pages/Leaderboard/CustomDropdown.jsx
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level3

#431 ✨ Neon button updated: blue in light mode, purple in dark mode , Card…
  src/components/SnippetComponents/NeonButton.jsx
  src/components/SnippetComponents/Snippets/NeonButtonSnippets.js
Labels: GSSoC'25, Level2

#448 Fixed errors in navbar
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level2

#450 Pricing section is completed
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/Pricing.jsx
Labels: GSSoC'25, Level2

#452 added prop validation in the seo
  src/components/SEO/SEO.jsx
Labels: GSSoC'25, Level2

#453 The sidebar of the explore page
  src/Pages/Dashboard/Dashboard.jsx
  src/Pages/Dashboard/SideBar.jsx
  src/components/SnippetComponents/AccordianSnippets.jsx
Labels: GSSoC'25, Level3

#467 Removed Clerk Authentication Code After Migration to MongoDB
  src/App.jsx
  src/Pages/Auth/ForgotPasswordPage.jsx
  src/components/UI/Modal.jsx
  src/components/layout/Navbar.jsx
  src/components/layout/WelcomeMessage.jsx
Labels: GSSoC'25, Level3

#462 Issue454
  src/App.jsx
  src/Pages/Contributors/ContributorGuide.jsx
  src/Pages/Home/HomePage.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#461 rounded off the multiple of 10
  src/Pages/Leaderboard/LeaderBoard.jsx
Labels: GSSoC'25, Level1

#484 [FIX]: #471 Abrupt Opening Animation in "Frequently Asked Questions" Dropdown
  src/Pages/Contact/FAQ.jsx
Labels: GSSoC'25, Level2

#485 [FIX]: #474 Inconsistent Hover Animations and Button Behavior on Home Page
  src/Pages/Home/HomePage.jsx
Labels: GSSoC'25, Level2

#490 Profile Route Integration, Bug Fixes & UI Polishing
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/profile.controller.js
  backend/src/routes/profile.route.js
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/Auth/LoginPage.jsx
  src/Pages/Auth/ProtectedRoute.jsx
  src/Pages/Auth/SignUpPage.jsx
  src/Pages/Profile/ProfilePage.jsx
Labels: GSSoC'25, Level3

#493 Enhanced the UI and also added multiple functionalities
  src/Pages/AnimationPlayground.jsx
Labels: GSSoC'25, Level3

#501 Updated and enhanced the UI with crazy animations
  src/components/Templates/TemplateCard.jsx
  src/components/Templates/TemplatesPage.jsx
Labels: GSSoC'25, Level3

#504 JavaScript Editor with Output Screen
  src/Pages/Playground/Code_Playground.jsx
  src/Pages/Playground/JavascriptCode.jsx
Labels: GSSoC'25, Level3

#508 Integrated Backend With Profile Page for Full Editing Functionality
  backend/src/controllers/profile.controller.js
  backend/src/routes/profile.route.js
  src/App.jsx
  src/Pages/Profile/ProfilePage.jsx
  src/components/UI/DarkModeToggle.jsx
  src/components/layout/Navbar.jsx
  src/providers/AuthProvider.jsx
  src/store/authStore.js
Labels: GSSoC'25, Level3

#513 511
  src/Pages/Playground/Code_Playground.jsx
  src/Pages/Playground/JavascriptCode.jsx
Labels: GSSoC'25, Level3

#537 This pull request fixes the placeholder issue in branch naming and corrects the push command usage.
  src/Pages/BlogPage.jsx
Labels: GSSoC'25, Level1

#543 Added a dark theme support in the chat bot components
  src/components/layout/Chatbot.jsx
Labels: GSSoC'25, Level2

#544 Added prop validation and resolve issue in the auth controller
  backend/src/controllers/auth.controller.js
  src/Pages/Home/Testimonial.jsx
Labels: GSSoC'25, Level2

#541 Added a new Loader
  src/components/layout/Loader.jsx
  src/providers/AuthProvider.jsx
Labels: GSSoC'25, Level3

#547 Updated the Blog Page UI
  src/Pages/BlogPage.jsx
Labels: GSSoC'25, Level3

#548 Added Email Verification Alert and Skeleton Loaders on Profile Components
  src/Pages/Profile/ProfilePage.jsx
  src/Pages/Profile/components/AllComponents.jsx
  src/Pages/Profile/components/PendingComponents.jsx
  src/Pages/Profile/components/RejectedComponents.jsx
  src/Pages/Profile/components/VerifyEmailReminder.jsx
Labels: GSSoC'25, Level3

#558 Completed the enhancement of the resourceHub page
  src/Pages/Profile/Resourcehub.jsx
Labels: GSSoC'25, Level3

#559 Updated the Products page
  src/components/Templates/Product.jsx
Labels: GSSoC'25, Level3

#562 feat: add 60+ new color palettes
  src/Pages/Profile/PalettesPage.jsx
Labels: GSSoC'25, Level2

#563 Added Dynamic Tailwind Playground
  src/App.jsx
  src/Pages/Playground/TailwindPlayground.jsx
  src/components/layout/Navbar.jsx
  src/components/layout/PlaygroundDropdown.jsx
Labels: GSSoC'25, Level3

#570 Add example environment configuration file
  .env.example
Labels: Level1

#572 Added a Random color Gradient button to the Gradient Playground.
  src/Pages/Playground/ColorGradientPlayground.jsx
Labels: GSSoC'25, Level2

#575 added new 3 tabgroups
  src/components/SnippetComponents/Snippets/Tab.js
Labels: GSSoC'25, Level3

#577 Added Controllers for blog
  backend/src/controllers/blog.controller.js
  backend/src/routes/blog.route.js
Labels: GSSoC'25, Level2

#579 feat: added svg playground
  src/App.jsx
  src/Pages/Playground/SVGPlayground.jsx
  src/components/layout/Navbar.jsx
Labels: GSSoC'25, Level3

#582 Fixed Blogs Route Issues and Rearranged Challenge Page
  backend/src/app.js
  backend/src/models/blog.model.js
  backend/src/routes/blog.route.js
  src/App.jsx
  src/Pages/Components/ComponentsPage.jsx
  src/Pages/Components/components/ComponentsSideBar.jsx
  src/Pages/challenge/ChallengeMode.jsx
  src/Pages/challenge/challengeData.js
Labels: GSSoC'25, Level2

#583 Added the color gradients
  src/Pages/Playground/ColorGradientPlayground.jsx
Labels: GSSoC'25, Level3

#584 Added Custom 404 Page, Removed Unnecessary Page Components, and Implemented Theme Toggle Shortcut
  src/App.jsx
  src/Pages/NotFoundPage/NotFoundPage.jsx
  src/components/UI/DarkModeToggle.jsx
Labels: GSSoC'25, Level3

#594 Added a my snippet form
  src/Pages/Dashboard/MySnippet.jsx
Labels: GSSoC'25, Level3

#595 Added a update Blog and getuserblog Controller
  backend/src/controllers/blog.controller.js
  backend/src/routes/blog.route.js
Labels: GSSoC'25, Level3

#597 removed greeting removed
  src/Pages/Home/DynamicGreeting.jsx
  src/Pages/Home/HomePage.jsx
Labels: GSSoC'25, Level1

#598 Created color Pallete Demo page
  src/Pages/Profile/PalettesPage.jsx
Labels: GSSoC'25, Level2

#599 fix responses in contact form
  src/Pages/Contact/ContactUs.jsx
Labels: GSSoC'25, Level2

#608 Added New Subscription Component & Removed Old Footer Version
  src/Pages/Home/HomePage.jsx
  src/Pages/Home/Subscribe.jsx
  src/components/layout/Footer.jsx
Labels: GSSoC'25, Level3

#613 Added Components Sidebar & New Components Page with Categories
  backend/index.js
  backend/src/models/components.model.js
  src/App.jsx
  src/Pages/Components/ComponentsPage.jsx
  src/Pages/Components/components/ComponentsSideBar.jsx
  src/components/layout/Footer.jsx
Labels: GSSoC'25, Level3

#614 Improved Svg Playground
  backend/src/app.js
  src/Pages/Playground/SVGPlayground.jsx
Labels: GSSoC'25, Level3

#615 Improved Tailwind Playground
  src/Pages/Playground/TailwindPlayground.jsx
Labels: GSSoC'25, Level3

#620 Fix: Display correct icons for light and dark modes
  src/components/UI/DarkModeToggle.jsx
Labels: GSSoC'25, Level1

#621 fix: Let's Connect button functionality
  .env.example
  CONTRIBUITING.md
  package-lock.json
  src/Pages/Contact/ContactUs.jsx
  src/main.jsx
Labels: GSSoC'25, Level2

#634 challenge page animation
  package-lock.json
  src/Pages/challenge/ChallengeMode.jsx
  src/main.jsx
Labels: GSSoC'25, Level3

#636 Fix: Only one FAQ item opens at a time (#230)
  backend/.env.example
  src/Pages/Contact/ContactUs.jsx
  src/Pages/Contact/FAQ.jsx
Labels: GSSoC'25, Level2
